# Generated by Django 6.0 on 2025-12-28 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('action_type', models.CharField(choices=[('slack_send_message', 'Slack: Send Message'), ('notion_create_page', 'Notion: Create Page'), ('notion_update_page', 'Notion: Update Page'), ('trello_create_card', 'Trello: Create Card'), ('trello_move_card', 'Trello: Move Card'), ('gcal_create_event', 'Google Calendar: Create Event'), ('gcal_list_events', 'Google Calendar: List Events')], max_length=50)),
                ('app_id', models.CharField(max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
