# Generated by Django 4.2.7 on 2025-12-27 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('sendgrid', 'SendGrid'), ('slack', 'Slack'), ('airtable', 'Airtable')], max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=500)),
                ('additional_config', models.JSONField(blank=True, default=dict)),
                ('is_connected', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'connected_apps',
            },
        ),
    ]
