# Generated by Django 6.0 on 2025-12-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('app_type', models.CharField(choices=[('slack', 'Slack'), ('notion', 'Notion'), ('trello', 'Trello'), ('google_calendar', 'Google Calendar')], max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('linked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('app_type', 'label')},
            },
        ),
    ]
